name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run tsc && pnpm run lint && pnpm run build
